name: Deploy to Firebase Hosting
on: workflow_dispatch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHRISTMAS_CALENDAR_9EF41 }}'
          channelId: live
          projectId: christmas-calendar-9ef41
